# Generated by Django 3.0.2 on 2020-01-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_email', models.EmailField(blank=True, max_length=70, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
